version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local
  phpmyadmin:
    driver: local
  docker-in-docker:
    driver: local

services:
  php:
    build:
      context: ./docker/php
      args:
        - PHP_TAG_PREFIX=latest
        - PHP_VERSION=8.0
        - PUID=1000
        - PGID=1000
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./docker/php/php8.0.ini:/usr/local/etc/php/php.ini
      - ./src/:/var/www:cached
      - docker-in-docker:/certs/client
    ports:
      - "9003"
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:10.0.75.1"
    environment:
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    networks:
      - backend
    links:
      - docker-in-docker

  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php
        - PHP_UPSTREAM_PORT=9000
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./src/:/var/www:cached
      - ./docker/logs/nginx/:/var/log/nginx
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/ssl/:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - frontend
      - backend

  mariadb:
    build:
      context: ./docker/mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./docker/data/mariadb:/var/lib/mysql
      - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306"
    environment:
      - TZ=Europe/Istanbul
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend

  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MAX_EXECUTION_TIME=600
      - MEMORY_LIMIT=256M
      - UPLOAD_LIMIT=2G
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  docker-in-docker:
    image: docker:19.03-dind
    environment:
      DOCKER_TLS_SAN: DNS:docker-in-docker
    privileged: true
    volumes:
      - ./src/:/var/www
      - docker-in-docker:/certs/client
    expose:
      - 2375
    networks:
      - backend
